apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 12.3.0
      helm:
        valueFiles:
          - '$baseValues/environments/portfolio/argocd/apps/grafana/values.yaml'
          - '$dsValues/environments/portfolio/argocd/apps/grafana/values-datasources.yaml'
          - '$alertValues/environments/portfolio/argocd/apps/grafana/values-alerting.yaml'

    # Base Core Values Reference
    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: main
      ref: baseValues

    # DataSources Values Reference
    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: feat/chatbot-instrumentation
      ref: dsValues

    # Alerting Values Reference
    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: main
      ref: alertValues

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true