admin:
  existingSecret: "grafana-admin-credentials"
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: false

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:445606683808:certificate/bced14e9-9cc5-49f1-b1fa-f762b4de535a"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: portfolio
  hosts:
    - grafana.creechlabs.dev

grafana.ini:
  server:
    root_url: https://grafana.creechlabs.dev
    serve_from_sub_path: false
  feature_toggles:
    publicDashboards: true
    traceQLStreaming: true
  security:
    allow_embedding: true
    cookie_secure: true
  auth.anonymous:
    enabled: true
    org_name: Public
    org_role: Viewer
    hide_version: true
  auth:
    disable_login_form: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi

nodeSelector:
  node-lifecycle: on-demand

priorityClassName: stable-node-critical