apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.57.3
      helm:
        valueFiles:
          - '$values/environments/portfolio/argocd/apps/fluentbit/values.yaml'

    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true