apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 6.1.0
      helm:
        valueFiles:
          - '$values/environments/portfolio/argocd/apps/mimir/values.yaml'

    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: feat/mimir-prom-backend
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true