apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-gateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
      chart: opentelemetry-collector
      targetRevision: 0.153.0
      helm:
        valueFiles:
          - '$values/environments/portfolio/argocd/apps/otel-gateway/values.yaml'

    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: feat/chatbot-instrumentation
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true