apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 13.6.1
      helm:
        valueFiles:
          - '$values/environments/portfolio/argocd/apps/loki/values.yaml'

    - repoURL: 'git@github.com:rosej904/creechlabs-terraform.git'
      targetRevision: feature/eks-observability
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true