grafana:
  url: "https://grafana.creechlabs.dev"
  apiKey: ""
  apiKeySecret:
    name: "grafana-mcp-token"
    key: "token"

extraArgs:
  - "--allowed-hosts=mcp.creechlabs.dev"

disableWrite: false

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:445606683808:certificate/bced14e9-9cc5-49f1-b1fa-f762b4de535a"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/group.name: portfolio
  hosts:
    - host: mcp.creechlabs.dev
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector:
  node-lifecycle: on-demand